'use client';

import { useEffect, useMemo, useState } from 'react';
import clsx from 'clsx';
import { Shell } from '../../components/Shell';
import { PrimarySidebar } from '../../components/PrimarySidebar';
import { useRequirePermission } from '../../hooks/useRequirePermission';
import { useBeneficiaryProfile } from '../../hooks/useBeneficiaryProfile';
import { useBeneficiaryForms } from '../../hooks/useBeneficiaryForms';
import { useTimelineEntries } from '../../hooks/useTimelineEntries';
import { useBeneficiaryConsents } from '../../hooks/useBeneficiaryConsents';
import { useActionPlans } from '../../hooks/useActionPlans';
import { FORM_SCHEMAS } from '../../data/formSchemas';
import type { FormSchema } from '../../types/form-schema';
import type { BeneficiaryProfile, BeneficiarySummary } from '../../types/beneficiaries';
import type { FormSubmissionSummary } from '../../types/forms';
import type { TimelineEvent } from '../../types/timeline';
import type { ConsentRecord } from '../../types/consents';
import type { ActionPlan, ActionPlanItem } from '../../types/action-plans';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { LoadingState } from '../../components/LoadingState';
import { FormRenderer } from '../../components/FormRenderer';
import { API_URL } from '../../lib/api';
