project              = "moveongs"
environment          = "dev"
aws_region           = "us-east-1"
availability_zones   = ["us-east-1a", "us-east-1b"]
vpc_cidr             = "10.30.0.0/16"
public_subnet_cidrs  = ["10.30.10.0/24", "10.30.11.0/24"]
private_subnet_cidrs = ["10.30.20.0/24", "10.30.21.0/24"]
container_image      = "ghcr.io/your-org/moveongs:latest"
desired_count        = 1
max_count            = 2
cpu                  = 512
memory               = 1024
create_rds           = true
rds_instance_class   = "db.t4g.small"
rds_allocated_storage = 20
rds_multi_az         = false
rds_password         = "change-me-dev"
create_redis         = true
redis_node_type      = "cache.t3.micro"
redis_num_cache_nodes = 1
jwt_secret_value     = "dev-secret-change-me"
allowed_ingress_cidrs = ["0.0.0.0/0"]
extra_environment = {
  OTEL_ENABLED                    = "true"
  OTEL_SERVICE_NAME               = "moveongs-api-dev"
  OTEL_EXPORTER_OTLP_ENDPOINT     = "https://otel.dev.your-domain.com"
  OTEL_TRACES_SAMPLER             = "parentbased_always_on"
}
