name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Unit & Integration tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      JWT_SECRET: testsecretthatshouldbereplacedwith32chars
      JWT_EXPIRES_IN: 1d
      LOG_LEVEL: warn
      OTEL_ENABLED: 'false'
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run check
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build

  lint-docker:
    name: Docker image build (validation)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build production image
        run: docker build -f deploy/docker/Dockerfile -t moveongs:test .
